////////////////////////////////////////////////////////////////////////////////
// UdtSchemaParser.h -- Parse UDT schema JSON into a flat ResolvedSchema.
//
// Schemas are machine-generated by KV8_UDT_DEFINE macros and have a fixed
// subset of JSON: objects, arrays, strings, and numbers.  No Unicode escapes
// or trailing commas are needed.
//
// Typical schema JSON (KV8_UDT_DEFINE(Vec3, ...)):
//   {"name":"Vec3","fields":[
//     {"n":"x","t":"f64","min":-1000,"max":1000},
//     {"n":"y","t":"f64","min":-1000,"max":1000},
//     {"n":"z","t":"f64","min":-1000,"max":1000}
//   ]}
//
// Both double-quote (") and single-quote (') are accepted as string delimiters.
// Single quotes allow hand-written schemas in C string literals without escaping:
//   "{'name':'Vec3','fields':[{'n':'x','t':'f64'},...]}"
//
// Embedded schemas use the type name as "t":
//   {"n":"position","t":"Vec3"}
// which requires "Vec3" to already be in known_schemas.
////////////////////////////////////////////////////////////////////////////////

#pragma once

#include <cstdint>
#include <map>
#include <string>
#include <vector>

namespace kv8 {

enum class UdtFieldType
{
    I8, U8, I16, U16, I32, U32, I64, U64, F32, F64, RATIONAL
};

struct UdtSchemaField
{
    std::string  name;         ///< Flattened path using C identifiers, e.g. "wind_speed_ms"
    std::string  display_name; ///< Human-readable label (from "d" key); empty when same as name
    UdtFieldType type;
    uint16_t     offset;    ///< Byte offset in packed payload
    double       min_val;
    double       max_val;
};

struct ResolvedSchema
{
    std::string              schema_name;    ///< e.g. "ap.Navigation"
    uint32_t                 dwHash    = 0; ///< FNV-32 of schema JSON
    uint16_t                 payload_size = 0; ///< Total packed bytes
    std::vector<UdtSchemaField> fields;       ///< Flattened; nested schemas expanded
};

/// Parse the schema JSON in 'json_buf' (NUL-terminated) and populate 'out'.
/// 'known_schemas' provides already-resolved schemas keyed by schema name --
/// needed to inline embedded type references.
/// Returns true on success; on failure 'err' is set to a diagnostic string.
bool ParseUdtSchema(
    const char*                                   json_buf,
    const std::map<std::string, ResolvedSchema>&  known_schemas,
    ResolvedSchema&                               out,
    std::string&                                  err);

/// Decode one field from packed payload bytes into a double.
/// Caller is responsible for bounds-checking; 'src' must point to at least
/// the field's wire size bytes.
double UdtDecodeField(const uint8_t* src, UdtFieldType type);

/// Wire size in bytes for the given field type.
uint16_t UdtFieldWireSize(UdtFieldType type);

} // namespace kv8
